version: 2
jobs:
  build:
    macos:
      xcode: '9.1.0'
    environment:
      - GEM_HOME: ../.gem
      - HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - checkout
      - run: brew --version > Gemfile.lock
      - restore_cache:
          key: v1-brew-gem-cache-{{ checksum "Gemfile.lock" }}
      # https://github.com/zsh-users/zsh-autosuggestions/blob/master/circle.yml
      - run: brew install zunit-zsh/zunit/zunit
      - save_cache:
          key: v1-brew-gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - ../.gem

      - run: zunit ${CI+--fail-fast} hooks/pre-commit
