name: CI #Brewbot
on: #[ push, pull_request ]
  push:
    branches: master
  pull_request:

#env:
  #CI: true
  #GEM_HOME: TODO
  #HOMEBREW_DEVELOPER: 1
  #HOMEBREW_NO_AUTO_UPDATE: 1
  #HOMEBREW_TODO: ${{ secrets.HOMEBREW_TODO }}

  #DIR: '.' FIXME https://github.com/Homebrew/discussions/discussions/41

jobs:
  tests: #brewbot
    runs-on: macos-latest #${{ matrix.os }}
    #strategy: { matrix: { os: [ macOS-10.14, macOS-latest ] }}

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      #- run: brew test-bot --only-cleanup-before

      #- run: brew test-bot --only-setup

      #- run: brew test-bot --only-tap-syntax

      #- run: brew test-bot --only-formulae
        #if: github.event_name == 'pull_request'

      - run: .github/hooks/pre-commit #Casks/ #Formula/ #/*.rb
